apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
  namespace: production
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.21.2
  replicas: 2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: storage
            operator: In
            values:
            - redis
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "500m"
